[simulation]
boxLength = 20           # m
exitWidth = 1.2         # m
pedestrians = 200       # units
minRadius = 0.15        # m
maxRadius = 0.32        # m
beta = 0.9
vdMax = 2.0             # m/s
dtSimulation = 0.001    # s
outputInterval = 10

[files]
staticInput = "./static.txt"
output = "./out/output.txt"