[simulation]
boxLength = 20          # m
exitWidth = 1.2         # m
pedestrians = 200       # units
minRadius = 0.10        # m
maxRadius = 0.37        # m
beta = 0.9              # unitless
vdMax = 2.0             # m/s
outputInterval = 5      # units

[files]
staticInput = "./static.txt"
output = "./out/output.txt"
benchmark = "./out/benchmark.txt"
